-- 1. example 계정 생성

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER example IDENTIFIED BY "oracle_1234";

GRANT RESOURCE, CONNECT TO example;

ALTER USER example DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-- 1-1. example2 계정 생성 DB연결 권한, VIEW 생성 권한 추가

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER example2 IDENTIFIED BY "oracle_1234";
GRANT RESOURCE, CONNECT TO example2;

GRANT CREATE VIEW TO example2;

--2. example2 계정 DB연결 권한 회수 후, 삭제

REVOKE CONNECT FROM example2; 
DROP USER example2 CASCADE;

-- 3. example 계정으로 접속하여 MEMBER 테이블과 BOARD 테이블 생성

-- MEMBER 테이블 생성 

CREATE TABLE MEMBER(
	MEMBER_NO   	 NUMBER NOT NULL, 
	MEMBER_ID   	 VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD  VARCHAR2(30) NOT NULL,
	PHONE_NUMBER 	 VARCHAR2(20),
	DELETE_YN   	 CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN('Y','N')),
	CONSTRAINT MEMBER_NO_PK PRIMARY KEY(MEMBER_NO));

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN IS '삭제여부';

-- BOARD 테이블 생성
CREATE TABLE "BOARD" (
	BOARD_NO	  NUMBER		 NOT NULL,
	BOARD_TITLE	  VARCHAR2(300)	 NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER  NUMBER,
	CREATE_DATE	  DATE	DEFAULT SYSDATE,
	CONSTRAINT BOARD_NO_PK PRIMARY KEY(BOARD_NO),
	FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN "BOARD".BOARD_NO IS '글번호';
COMMENT ON COLUMN "BOARD".BOARD_TITLE IS '글제목';
COMMENT ON COLUMN "BOARD".BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN "BOARD".BOARD_WRITER IS '작성자';
COMMENT ON COLUMN "BOARD".CREATE_DATE IS '작성일자';


-- 4. MEMBER 테이블과 BOARD 테이블 생성
-- 단, 회원번호와 글번호는 시퀀스를 생성하여 추가

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 100
NOCYCLE
NOCACHE;

INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step1', 'step11', NULL, DEFAULT);
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step2', 'step22', '010-1111-2222', DEFAULT);
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step3', 'step33', NULL, DEFAULT);


CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO "BOARD"
VALUES(SEQ_BOARD_NO.NEXTVAL, '첫 글', '스텝평가', 100, DEFAULT);
INSERT INTO "BOARD"
VALUES(SEQ_BOARD_NO.NEXTVAL, '두 번째 글', '재밌다', 200, DEFAULT);
INSERT INTO "BOARD"
VALUES(SEQ_MEMBER_NO.NEXTVAL, '세 번째 글', '하하하', 300, DEFAULT);

-- 5. SELECT문 작성
SELECT BOARD_NO, BOARD_CONTENT, MEMBER_ID, CREATE_DATE
FROM "BOARD"
JOIN MEMBER ON(BOARD_WRITER = MEMBER_NO)
ORDER BY BOARD_NO DESC;





